global using System;
global using System.Runtime.InteropServices;
global using System.Threading;
global using System.Threading.Tasks;
global using Community.VisualStudio.Toolkit;
global using Microsoft.VisualStudio;
global using Microsoft.VisualStudio.Shell;
global using Microsoft.VisualStudio.Shell.Interop;
global using Microsoft.VisualStudio.TextManager.Interop;